# Site settings
name: Michael Dai CLE10
email: michealxia7@gmail.com
author: Michael Dai
url: http://social.michaeldai.com
resume_site: 
github: https://github.com/michaeldai7/
baseurl: ""
description: Actually, less is more!
meta_description: 
motto: 
banner: 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: michaeldai7

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

